name: Deploy IBM Cloud CF
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to IBM Cloud Foundry
        uses: IBM/cloudfoundry-deploy@master
        with:
          IBM_CLOUD_API_KEY: rJNtIVOcq45RxF9Q_FB8szhbjrbkAPnYLFCw3MkZOrWD
          IBM_CLOUD_CF_API: api.us-south.cf.cloud.ibm.com
          IBM_CLOUD_CF_ORG: lameranha@gmail.com
          IBM_CLOUD_CF_SPACE: dev
